packages:
  - 'packages/*'

catalog:
  '@baejino/auth': 0.1.1
  '@blocknote/server-util': ^0.46.2
  '@graphql-tools/schema': ^10.0.31
  '@graphql-tools/utils': ^11.0.0
  '@prisma/client': ^6.19.3
  diff: ^9.0.0
  express: ^5.2.1
  express-rate-limit: 8.5.1
  express-session: ^1.19.0
  express-winston: ^4.2.0
  graphql-http: ^1.22.4
  lusca: ^1.7.0
  prisma: ^6.19.3
  sqlite3: ^6.0.1
  winston: ^3.19.0
