export interface ContentBlock {
    id: string;
    [key: string]: unknown;
}

const isBlock = (value: unknown): value is ContentBlock =>
    typeof value === 'object' && value !== null && 'id' in value && typeof value.id === 'string';

const parseBlocks = (content: string): ContentBlock[] => {
    const value: unknown = JSON.parse(content || '[]');
    if (!Array.isArray(value) || !value.every(isBlock)) {
        throw new Error('Invalid note content');
    }
    return value;
};

// MCP Markdown conversion can regenerate block IDs. Compare document values instead.
const canonicalValue = (value: unknown): unknown => {
    if (Array.isArray(value)) return value.map(canonicalValue);
    if (typeof value !== 'object' || value === null) return value;
    return Object.fromEntries(
        Object.entries(value)
            .filter(([key]) => !(key === 'id' && 'type' in value && 'children' in value))
            .sort(([left], [right]) => left.localeCompare(right))
            .map(([key, child]) => [key, canonicalValue(child)]),
    );
};

export interface NoteContentChanges {
    blockIds: string[];
    deletedCount: number;
}

export interface NoteReviewEntry {
    kind: 'modified' | 'added' | 'deleted';
    before?: ContentBlock;
    after?: ContentBlock;
    anchorId?: string;
}

const getBlockType = (block: ContentBlock) => (typeof block.type === 'string' ? block.type : 'unknown');

const pairChangedRun = (removed: ContentBlock[], added: ContentBlock[], anchorId?: string): NoteReviewEntry[] => {
    if (!removed.length) {
        return added.map((after) => ({ kind: 'added', after, anchorId }));
    }
    if (!added.length) {
        return removed.map((before) => ({ kind: 'deleted', before, anchorId }));
    }

    const rows = removed.length;
    const columns = added.length;
    // Very large rewrites should stay bounded and, most importantly, must not claim
    // that two different block types are a before/after pair.
    if (rows * columns > 250_000) {
        const entries: NoteReviewEntry[] = [];
        for (let index = 0; index < Math.max(rows, columns); index++) {
            const before = removed[index];
            const after = added[index];
            if (before && after && getBlockType(before) === getBlockType(after)) {
                entries.push({ kind: 'modified', before, after, anchorId });
            } else {
                if (before) entries.push({ kind: 'deleted', before, anchorId });
                if (after) entries.push({ kind: 'added', after, anchorId });
            }
        }
        return entries;
    }

    // IDs are often regenerated by the MCP Markdown conversion. Match changed
    // blocks by their structural type so a removed paragraph is never presented
    // as the "Before" value of an updated checklist, heading, table, and so on.
    const lengths = Array.from({ length: rows + 1 }, () => new Uint32Array(columns + 1));
    for (let i = rows - 1; i >= 0; i--) {
        for (let j = columns - 1; j >= 0; j--) {
            lengths[i][j] =
                getBlockType(removed[i]) === getBlockType(added[j])
                    ? lengths[i + 1][j + 1] + 1
                    : Math.max(lengths[i + 1][j], lengths[i][j + 1]);
        }
    }

    const entries: NoteReviewEntry[] = [];
    let i = 0;
    let j = 0;
    while (i < rows || j < columns) {
        if (i < rows && j < columns && getBlockType(removed[i]) === getBlockType(added[j])) {
            entries.push({ kind: 'modified', before: removed[i], after: added[j], anchorId });
            i++;
            j++;
        } else if (j < columns && (i === rows || lengths[i][j + 1] > lengths[i + 1][j])) {
            entries.push({ kind: 'added', after: added[j], anchorId });
            j++;
        } else {
            entries.push({ kind: 'deleted', before: removed[i], anchorId });
            i++;
        }
    }
    return entries;
};

export const findUnchangedBlock = (before: string, after: string, blockId: string): string | undefined => {
    const previous = parseBlocks(before);
    const index = previous.findIndex((block) => block.id === blockId);
    if (index < 0) return undefined;
    const signature = JSON.stringify(canonicalValue(previous[index]));
    const occurrence = previous
        .slice(0, index)
        .filter((block) => JSON.stringify(canonicalValue(block)) === signature).length;
    return parseBlocks(after).filter((block) => JSON.stringify(canonicalValue(block)) === signature)[occurrence]?.id;
};

export const getNoteReview = (before: string, after: string): NoteReviewEntry[] => {
    const previous = parseBlocks(before);
    const next = parseBlocks(after);
    const left = previous.map((block) => JSON.stringify(canonicalValue(block)));
    const right = next.map((block) => JSON.stringify(canonicalValue(block)));
    let start = 0;
    while (start < left.length && start < right.length && left[start] === right[start]) start++;
    let leftEnd = left.length;
    let rightEnd = right.length;
    while (leftEnd > start && rightEnd > start && left[leftEnd - 1] === right[rightEnd - 1]) {
        leftEnd--;
        rightEnd--;
    }

    const rows = leftEnd - start;
    const columns = rightEnd - start;
    // Bound work for unusually large rewrites; highlight the changed range in that case.
    const entries: NoteReviewEntry[] = [];
    const appendRun = (removed: ContentBlock[], added: ContentBlock[], anchorId?: string) => {
        entries.push(...pairChangedRun(removed, added, anchorId));
    };
    if (rows * columns > 250_000) {
        appendRun(previous.slice(start, leftEnd), next.slice(start, rightEnd), next[rightEnd]?.id);
        return entries;
    }
    const lengths = Array.from({ length: rows + 1 }, () => new Uint32Array(columns + 1));
    for (let i = rows - 1; i >= 0; i--) {
        for (let j = columns - 1; j >= 0; j--) {
            lengths[i][j] =
                left[start + i] === right[start + j]
                    ? lengths[i + 1][j + 1] + 1
                    : Math.max(lengths[i + 1][j], lengths[i][j + 1]);
        }
    }
    let removed: ContentBlock[] = [];
    let added: ContentBlock[] = [];
    let i = 0;
    let j = 0;
    while (i < rows || j < columns) {
        if (i < rows && j < columns && left[start + i] === right[start + j]) {
            appendRun(removed, added, next[start + j].id);
            removed = [];
            added = [];
            i++;
            j++;
        } else if (j < columns && (i === rows || lengths[i][j + 1] >= lengths[i + 1][j])) {
            added.push(next[start + j]);
            j++;
        } else {
            removed.push(previous[start + i]);
            i++;
        }
    }
    appendRun(removed, added, next[rightEnd]?.id);
    return entries;
};

export const getNoteContentChanges = (before: string, after: string): NoteContentChanges => {
    const entries = getNoteReview(before, after);
    return {
        blockIds: entries.flatMap((entry) => (entry.after ? [entry.after.id] : [])),
        deletedCount: entries.filter((entry) => entry.kind === 'deleted').length,
    };
};

export const getReviewText = (value: unknown): string => {
    if (typeof value === 'string') return value;
    if (Array.isArray(value)) return value.map(getReviewText).join('');
    if (typeof value !== 'object' || value === null) return '';
    if ('text' in value && typeof value.text === 'string') return value.text;
    if ('rows' in value && Array.isArray(value.rows)) return value.rows.map(getReviewText).join('\n');
    if ('cells' in value && Array.isArray(value.cells)) return value.cells.map(getReviewText).join(' | ');
    if ('content' in value) {
        const children = 'children' in value && Array.isArray(value.children) ? value.children : [];
        const props = 'props' in value && typeof value.props === 'object' && value.props !== null ? value.props : {};
        const prefix =
            'type' in value && value.type === 'checkListItem'
                ? 'checked' in props && props.checked
                    ? '☑ '
                    : '☐ '
                : '';
        return [prefix + getReviewText(value.content), ...children.map(getReviewText)].filter(Boolean).join('\n');
    }
    if ('props' in value && typeof value.props === 'object' && value.props !== null) {
        if ('title' in value.props) return String(value.props.title);
        if ('name' in value.props) return String(value.props.name);
    }
    return '';
};
