export {
    MagnifyingGlass as Search,
    X as Close,
    List as Menu,
    List,
    PencilSimple as Pencil,
    PushPin as Pin,
    Gear,
    Calendar,
    Bell,
    Tag,
    GridFour as Grid,
    DotsThreeVertical as VerticalDots,
    Trash as TrashCan,
    CaretLeft as ChevronLeft,
    CaretRight as ChevronRight,
    CaretRight as TriangleRight,
    CaretDown as TriangleDown,
    CaretUp as TriangleUp,
    Check,
    Plus,
    Minus,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    CaretDown as ChevronDown,
    CaretUp as ChevronUp,
    Eye,
    EyeSlash,
    Copy,
    Share,
    Download,
    Upload,
    Link as LinkIcon,
    Image,
    File,
    Folder,
    FolderOpen,
    House as Home,
    User,
    Users,
    Heart,
    Star,
    BookmarkSimple as Bookmark,
    Clock,
    Warning,
    Info,
    Question,
    CheckCircle,
    XCircle,
    WarningCircle,
    Spinner,
    SortAscending,
    SortDescending,
    Funnel as Filter,
    MagnifyingGlassPlus as ZoomIn,
    MagnifyingGlassMinus as ZoomOut,
    TextAa as Text,
    TextB as Bold,
    TextItalic as Italic,
    TextUnderline as Underline,
    ListBullets,
    ListNumbers,
    Quotes as Quote,
    Code,
    Table,
    LinkSimple,
    Paperclip as Attachment,
    Sun,
    Moon,
    Desktop,
    DeviceMobile as Mobile,
    Palette,
    Sliders as Settings,
    Power,
    SignOut,
    SignIn,
    ArrowClockwise as Refresh,
    ArrowCounterClockwise as Undo,
    ArrowUUpRight as Redo,
    FloppyDisk as Save,
    PencilLine as Edit,
    Eraser,
    Selection,
    Hand,
    Crosshair,
    Circle,
    Square,
    Triangle,
    Play,
    Pause,
    Stop,
    SkipBack,
    SkipForward,
    SpeakerHigh as VolumeUp,
    SpeakerLow as VolumeDown,
    SpeakerX as VolumeMute
} from '@phosphor-icons/react';
