import type { ThemePackage, ThemeVariableMap } from '~/models/theme.model';

export const STUDIO_PACKAGE_ID = 'ocean-brain.studio';
export const STUDIO_LIGHT_THEME_ID = `${STUDIO_PACKAGE_ID}/light`;
export const STUDIO_DARK_THEME_ID = `${STUDIO_PACKAGE_ID}/dark`;
export const SKETCHBOOK_PACKAGE_ID = 'ocean-brain.sketchbook';
export const SKETCHBOOK_LIGHT_THEME_ID = `${SKETCHBOOK_PACKAGE_ID}/light`;
export const SKETCHBOOK_DARK_THEME_ID = `${SKETCHBOOK_PACKAGE_ID}/dark`;

export const STUDIO_THEME_PACKAGE = {
    schemaVersion: 1,
    id: STUDIO_PACKAGE_ID,
    name: 'Studio',
    version: '1.0.0',
    author: 'Ocean Brain',
    description: 'The default Ocean Brain interface.',
    themes: [
        { id: 'light', label: 'Studio Light', appearance: 'light' },
        { id: 'dark', label: 'Studio Dark', appearance: 'dark' },
    ],
} satisfies ThemePackage;

const sketchbookVariables = {
    '--palette-yellow': '#fcebaf',
    '--palette-green': '#b2e0b2',
    '--palette-pink': '#ffb3c1',
    '--palette-orange': '#ffccb3',
    '--palette-blue': '#a4d8e1',
    '--palette-purple': '#e1b7e1',
    '--palette-teal': '#a4dbd6',
    '--palette-lavender': '#e1c6e7',
    '--priority-high': '#e88f9d',
    '--priority-medium': '#e9b27f',
    '--priority-low': '#d8c36e',
    '--ob-font-ui': 'Gaegu, Pretendard, sans-serif',
    '--ob-font-editor': 'Gaegu, Pretendard, sans-serif',
    '--ob-font-graph': 'Gaegu, Pretendard, sans-serif',
    '--ob-radius-control-sm': '6px 2px 7px 2px / 2px 5px 2px 6px',
    '--ob-radius-control-md': '10px 3px 11px 3px / 3px 8px 3px 10px',
    '--ob-radius-control-lg': '12px 4px 13px 3px / 4px 10px 4px 12px',
    '--ob-radius-item': '10px 3px 11px 3px / 3px 8px 3px 10px',
    '--ob-radius-surface': '18px 5px 20px 4px / 5px 16px 5px 18px',
    '--ob-radius-floating': '14px 4px 16px 3px / 4px 13px 4px 15px',
    '--ob-radius-dialog': '20px 6px 22px 5px / 6px 18px 6px 20px',
    '--ob-radius-dialog-compact': '15px 4px 17px 4px / 4px 14px 4px 16px',
    '--ob-border-control-width': '2px',
    '--ob-border-surface-width': '2px',
    '--ob-border-style': 'solid',
    '--ob-shadow-control': '3px 3px 0px 0px #352f2938',
    '--ob-shadow-surface': '4px 4px 0px 0px #352f2933',
    '--ob-shadow-floating': '5px 5px 0px 0px #352f293d',
    '--ob-shadow-dialog': '7px 7px 0px 0px #352f2942',
    '--ob-shadow-dialog-compact': '5px 5px 0px 0px #352f293d',
    '--ob-shadow-dialog-form': '7px 7px 0px 0px #352f2942',
    '--ob-shadow-dialog-inspect': '7px 7px 0px 0px #352f2942',
    '--ob-shadow-dialog-confirm': '5px 5px 0px 0px #352f293d',
    '--ob-shadow-shell-control': '4px 4px 0px 0px #352f293d',
} satisfies ThemeVariableMap;

const sketchbookLightVariables = {
    '--page-bg': '#fdf8f3',
    '--surface': '#fffcf7',
    '--muted': '#f7ede1',
    '--subtle': '#fff9f0eb',
    '--elevated': '#fcebaf',
    '--emphasis': '#ffccb3',
    '--hover': '#fcebaf80',
    '--hover-subtle': '#fcebaf4d',
    '--active': '#fcebafb3',
    '--ghost': '#fcebaf',
    '--fg': '#2e2924',
    '--fg-default': '#3b342e',
    '--fg-muted': '#574d44',
    '--fg-secondary': '#6b5f55',
    '--fg-tertiary': '#83756a',
    '--fg-disabled': '#b9aa9d',
    '--fg-placeholder': '#95867a',
    '--fg-error': '#9f3f4c',
    '--fg-on-accent': '#2f2923',
    '--fg-on-filled': '#2f2923',
    '--fg-weekend': '#bd4f68',
    '--border': '#554b42',
    '--border-secondary': '#9b8979',
    '--border-subtle': '#ddcdbc',
    '--border-focus': '#554b42',
    '--border-error': '#be6570',
    '--accent-primary': '#5dade2',
    '--accent-primary-hover': '#4a9ac8',
    '--accent-secondary': '#5dade2',
    '--accent-secondary-hover': '#4a9ac8',
    '--accent-danger': '#ffb3c1',
    '--accent-danger-hover': '#f49baa',
    '--accent-success': '#8fbc91',
    '--accent-success-hover': '#79aa7c',
    '--accent-soft-primary': '#5dade24d',
    '--accent-soft-primary-hover': '#5dade280',
    '--accent-soft-danger': '#d96e7e3d',
    '--accent-soft-danger-hover': '#d96e7e57',
    '--accent-soft-success': '#8fbc9142',
    '--accent-soft-success-hover': '#8fbc915c',
    '--cta': '#fcebaf',
    '--cta-hover': '#ffccb3',
    '--overlay': '#352b235c',
    '--highlight': '#d4edff',
    '--highlight-fg': '#3b342e',
    '--divider': '#d9c6b4',
    '--ob-graph-background': '#fbf2e8',
    '--ob-graph-node-hub': '#433a33',
    '--ob-graph-node-selected': '#2f2924',
    '--ob-graph-node-connected': '#6f655b',
    '--ob-graph-node-default-1': '#f2d37f',
    '--ob-graph-node-default-2': '#9ecfd5',
    '--ob-graph-node-default-3': '#a9d3aa',
    '--ob-graph-node-default-4': '#dfb5dc',
    '--ob-graph-node-dimmed-1': '#f2d37f4a',
    '--ob-graph-node-dimmed-2': '#9ecfd547',
    '--ob-graph-node-dimmed-3': '#a9d3aa47',
    '--ob-graph-node-dimmed-4': '#dfb5dc42',
    '--ob-graph-node-hub-dimmed': '#433a332e',
    '--ob-graph-node-stroke': '#fffaf3',
    '--ob-graph-node-selected-stroke': '#8b796a',
    '--ob-graph-label-background': '#fffaf3eb',
    '--ob-graph-label-text': '#3b342e',
    '--ob-graph-link-idle': '#6f655b66',
    '--ob-graph-link-connected': '#554b42',
    '--ob-graph-link-dimmed': '#6f655b24',
    '--ob-graph-legend-hub': '#433a33',
} satisfies ThemeVariableMap;

const sketchbookDarkVariables = {
    '--page-bg': '#1a1714',
    '--surface': '#252220',
    '--muted': '#2d2925',
    '--subtle': '#332e29c7',
    '--elevated': '#2b2723',
    '--emphasis': '#3b342e',
    '--hover': '#f6e8d916',
    '--hover-subtle': '#f6e8d90d',
    '--active': '#f6e8d924',
    '--ghost': '#f6e8d916',
    '--fg': '#fff7ed',
    '--fg-default': '#f4eadf',
    '--fg-muted': '#ded0c1',
    '--fg-secondary': '#c5b6a7',
    '--fg-tertiary': '#9f9184',
    '--fg-disabled': '#645b53',
    '--fg-placeholder': '#84786d',
    '--fg-error': '#f0a0aa',
    '--fg-on-accent': '#2e2924',
    '--fg-on-filled': '#2e2924',
    '--fg-weekend': '#f0a0b0',
    '--border': '#9c8d7f',
    '--border-secondary': '#75695f',
    '--border-subtle': '#403932',
    '--border-focus': '#e4d2bf',
    '--border-error': '#e9959f',
    '--accent-primary': '#e8cb7d',
    '--accent-primary-hover': '#f0d990',
    '--accent-secondary': '#8fc2c9',
    '--accent-secondary-hover': '#a6d2d7',
    '--accent-danger': '#d97885',
    '--accent-danger-hover': '#e68e99',
    '--accent-success': '#91bc92',
    '--accent-success-hover': '#a8cda9',
    '--accent-soft-primary': '#e8cb7d2e',
    '--accent-soft-primary-hover': '#e8cb7d47',
    '--accent-soft-danger': '#d9788529',
    '--accent-soft-danger-hover': '#d9788542',
    '--accent-soft-success': '#91bc9229',
    '--accent-soft-success-hover': '#91bc9242',
    '--cta': '#f1dfc8',
    '--cta-hover': '#fff0dc',
    '--overlay': '#0b0907a3',
    '--highlight': '#e8cb7d33',
    '--highlight-fg': '#fff7ed',
    '--divider': '#463e37',
    '--ob-shadow-control': '3px 3px 0px 0px #00000057',
    '--ob-shadow-surface': '4px 4px 0px 0px #00000052',
    '--ob-shadow-floating': '6px 6px 0px 0px #0000005c',
    '--ob-shadow-dialog': '7px 7px 0px 0px #0000005c',
    '--ob-shadow-dialog-compact': '5px 5px 0px 0px #0000005c',
    '--ob-shadow-dialog-form': '7px 7px 0px 0px #0000005c',
    '--ob-shadow-dialog-inspect': '7px 7px 0px 0px #0000005c',
    '--ob-shadow-dialog-confirm': '5px 5px 0px 0px #0000005c',
    '--ob-shadow-shell-control': '4px 4px 0px 0px #0000005c',
    '--ob-graph-background': '#201c18',
    '--ob-graph-node-hub': '#f0dfca',
    '--ob-graph-node-selected': '#fff4e5',
    '--ob-graph-node-connected': '#c5b39f',
    '--ob-graph-node-default-1': '#6b5939',
    '--ob-graph-node-default-2': '#3f6266',
    '--ob-graph-node-default-3': '#48634b',
    '--ob-graph-node-default-4': '#654e63',
    '--ob-graph-node-dimmed-1': '#6b593947',
    '--ob-graph-node-dimmed-2': '#3f626642',
    '--ob-graph-node-dimmed-3': '#48634b42',
    '--ob-graph-node-dimmed-4': '#654e633d',
    '--ob-graph-node-hub-dimmed': '#f0dfca2e',
    '--ob-graph-node-stroke': '#2b2520',
    '--ob-graph-node-selected-stroke': '#bca68e',
    '--ob-graph-label-background': '#211d19eb',
    '--ob-graph-label-text': '#f4eadf',
    '--ob-graph-link-idle': '#c5b39f5c',
    '--ob-graph-link-connected': '#e0cbb4',
    '--ob-graph-link-dimmed': '#c5b39f1f',
    '--ob-graph-legend-hub': '#f0dfca',
} satisfies ThemeVariableMap;

export const SKETCHBOOK_THEME_PACKAGE = {
    schemaVersion: 1,
    id: SKETCHBOOK_PACKAGE_ID,
    name: 'Sketchbook',
    version: '1.0.0',
    author: 'Ocean Brain',
    description: 'Warm paper, irregular corners, and hand-drawn depth inspired by early Ocean Brain.',
    themes: [
        {
            id: 'light',
            label: 'Sketchbook Light',
            appearance: 'light',
            texture: 'paper',
            variables: { ...sketchbookVariables, ...sketchbookLightVariables },
        },
        {
            id: 'dark',
            label: 'Sketchbook Dark',
            appearance: 'dark',
            texture: 'paper',
            variables: { ...sketchbookVariables, ...sketchbookDarkVariables },
        },
    ],
} satisfies ThemePackage;

export const BUILT_IN_THEME_PACKAGES: ThemePackage[] = [STUDIO_THEME_PACKAGE, SKETCHBOOK_THEME_PACKAGE];
